Add ECC support to axi_llc
pulp-platform/axi_llc pull request #13
Opened 2024-04-16 20:18 UTC by Aquaticfuller

2024-05-12 21:40 UTC, yvantor requested changes
I added some comments requesting changes, but overall good job!

2024-05-12 21:40 UTC, yvantor commented on src/axi_llc_reg_wrap.sv
> +  );
Like above, if the `EnableEcc` is not set we probably do not want to have ECC-related buses and connections. I would suggest grouping them into an `if/else` generative like the following:
```suggestion
if (EnableEcc) begin: gen_ecc_connection
  logic [SetAssociativity-1:0][ EccSignalWidthPerAssoc - 1 : 0]  scrub_trigger;
  logic [SetAssociativity-1:0][ EccSignalWidthPerAssoc - 1 : 0]  scrubber_fix;
  logic [SetAssociativity-1:0][ EccSignalWidthPerAssoc - 1 : 0]  scrub_uncorrectable;
  logic [SetAssociativity-1:0][ EccSignalWidthPerAssoc - 1 : 0]  single_error;
  logic [SetAssociativity-1:0][ EccSignalWidthPerAssoc - 1 : 0]  multi_error;

  logic [SetAssociativity * EccSignalWidthPerAssoc - 1 : 0]  scrub_trigger_flat;
  logic [SetAssociativity * EccSignalWidthPerAssoc - 1 : 0]  scrubber_fix_flat;
  logic [SetAssociativity * EccSignalWidthPerAssoc - 1 : 0]  scrub_uncorrectable_flat;
  logic [SetAssociativity * EccSignalWidthPerAssoc - 1 : 0]  single_error_flat;
  logic [SetAssociativity * EccSignalWidthPerAssoc - 1 : 0]  multi_error_flat;

  for (genvar i = 0; unsigned'(i) < SetAssociativity; i++) begin : gen_ecc_signals_flat_i
    for (genvar j = 0; unsigned'(j) < EccSignalWidthPerAssoc ; j++) begin : gen_ecc_signals_flat_j
      assign scrub_trigger   [i][j] = scrub_trigger_flat[i * EccSignalWidthPerAssoc + j];
      assign scrubber_fix_flat        [i * EccSignalWidthPerAssoc + j] = scrubber_fix       [i][j];
      assign scrub_uncorrectable_flat [i * EccSignalWidthPerAssoc + j] = scrub_uncorrectable[i][j];
      assign single_error_flat        [i * EccSignalWidthPerAssoc + j] = single_error       [i][j];
      assign multi_error_flat         [i * EccSignalWidthPerAssoc + j] = multi_error        [i][j];
    end
  end

  assign llc_reg_req_en  = conf_req_i.addr[axi_llc_reg_pkg::BlockAw-1:0] < ecc_manager_reg_pkg::OffsetStart;

  // demux to send the req to llc_reg/ecc_reg
  reg_demux #(
    .req_t   ( reg_req_t  ),
    .rsp_t   ( reg_resp_t ),
    .NoPorts ( NumRegBus )
  ) i_reg_demux (
    .clk_i,
    .rst_ni,
    .in_req_i    ( conf_req_i     ),
    .in_rsp_o    ( conf_resp_o    ),
    .out_req_o   ( llc_reg_req    ),
    .out_rsp_i   ( llc_reg_resp   ),
    .in_select_i ( llc_reg_req_en )
  );
  
    // ECC manager, the offset of its memory mapped regs are started from the end of llc_reg
  ecc_manager #(
    .NumBanks      ( EccSignalWidth ),
    .ecc_mgr_req_t ( reg_req_t  ),
    .ecc_mgr_rsp_t ( reg_resp_t )
  ) i_llc_ecc_manager (
    .clk_i,
    .rst_ni,

    .ecc_mgr_req_i          ( llc_reg_req[1]  ),
    .ecc_mgr_rsp_o          ( llc_reg_resp[1] ),

    .bank_faults_i          ( single_error_flat | multi_error_flat ),
    .scrub_fix_i            ( scrubber_fix_flat        ),
    .scrub_uncorrectable_i  ( scrub_uncorrectable_flat ),
    .scrub_trigger_o        ( scrub_trigger_flat       ),
    .test_write_mask_no     ( /* not used */      )
  );
  end else begin: gen_no_ecc_connection
  assign llc_reg_req[0] = conf_req_i;
  assign conf_resp_o = llc_reg_resp[0];
  end
```

2024-05-12 21:40 UTC, yvantor commented on src/axi_llc_reg_wrap.sv
> +  );
(Probably some of the connections must be rearranged if the parameter is set to zero, to be checked)

2024-05-12 21:40 UTC, yvantor commented on src/axi_llc_reg_wrap.sv
> +    .reg_rsp_o  ( llc_reg_resp  ),
```suggestion
    .reg_req_i  ( llc_reg_req[0]   ),
    .reg_rsp_o  ( llc_reg_resp[0]  ),
```

2024-05-12 21:40 UTC, yvantor commented on src/axi_llc_reg_wrap.sv
> +    .test_write_mask_no     ( /* not used */      )
To be removed, consider including this into an `if/else` generative like the above.

2024-05-12 21:40 UTC, yvantor commented on src/axi_llc_sram.sv
> +    end
```suggestion
    always_ff @(posedge clk_i or negedge rst_ni) begin
      if(~rst_ni) begin
        hsk_q <= 1'b0;
        we_q  <= 1'b0;
        rdata_q <= '0;
      end else begin
        hsk_q <= hsk_d;
        we_q  <= we_i;
        if (rdata_en)
          rdata_q <= rdata_d;
      end
    end
```

2024-05-12 21:40 UTC, yvantor commented on src/axi_llc_sram.sv
> +    end
Delete, unify flip flops.

2024-05-12 21:40 UTC, yvantor commented on src/axi_llc_top.sv
> +  output logic [Cfg.SetAssociativity-1:0][(Cfg.TagEccGranularity ? (1'b1 << ($clog2(Cfg.TagLength + 32'd2)))/Cfg.TagEccGranularity : 1)+(Cfg.DataEccGranularity ? Cfg.BlockSize/Cfg.DataEccGranularity
See above comment on parameters.

2024-05-12 21:40 UTC, yvantor commented on src/axi_llc_top.sv
> +`endif
I would remove the define, the multi_error signal would be tied to 0 in the logic if the `EnableEcc` parameter is 0.

2024-05-12 21:40 UTC, yvantor commented on src/axi_llc_top.sv
> +  end
Check the `assign {data_sram_scrub_trigger[i], tag_sram_scrub_trigger[i]} = '0;`

```suggestion
if (EnableEcc) begin: gen_ecc_connections
  for (genvar i = 0; unsigned'(i) < Cfg.SetAssociativity; i++) begin : gen_ecc_signals
    assign {data_sram_scrub_trigger[i], tag_sram_scrub_trigger[i]} = '0;
    assign scrubber_fix_o[i]         = {data_sram_scrubber_fix[i],        tag_sram_scrubber_fix[i]};
    assign scrub_uncorrectable_o[i]  = {data_sram_scrub_uncorrectable[i], tag_sram_scrub_uncorrectable[i]};
    assign single_error_o[i]         = {data_sram_single_error[i],        tag_sram_single_error[i]};
    assign multi_error_o[i]          = {data_sram_multi_error[i],    tag_sram_multi_error[i]};
  end
end else begin: gen_no_ecc_connections
    assign scrubber_fix_o         = '0;
    assign scrub_uncorrectable_o  = '0;
    assign single_error_o         = '0;
    assign multi_error_o          = '0;
end
```

2024-05-12 21:40 UTC, yvantor commented on src/axi_llc_top.sv
> +`endif
Change this accordingly with the parameter.

2024-05-12 21:40 UTC, yvantor commented on src/axi_llc_top.sv
> +  logic [31:0] target_addr_lb, target_addr_ub;
Are these fixed to 32-bit?

2024-05-12 21:40 UTC, yvantor commented on src/axi_llc_write_unit.sv
> +`endif
Turn to parameter-based.

2024-05-12 21:40 UTC, yvantor commented on src/hit_miss_detect/axi_llc_tag_store.sv
> +  output logic [Cfg.SetAssociativity-1:0][(Cfg.TagEccGranularity ? (1'b1 << ($clog2(Cfg.TagLength + 32'd2)))/Cfg.TagEccGranularity : 1)-1:0]  multi_error_o
See above comments on parameters.

2024-05-12 21:40 UTC, yvantor commented on src/hit_miss_detect/axi_llc_tag_store.sv
> +  `FF(res_sram_wr_delay_q, res_sram_wr_delay_d, '0)
Please use [FFARN](https://github.com/pulp-platform/common_cells/blob/master/include/common_cells/registers.svh#L78)

2024-05-21 10:04 UTC, Aquaticfuller commented on Bender.lock
> +    revision: a466340ef514979f864c7b4fee49976943fe9c3f
I'm using the zx/astral_ecc_llc branch

2024-06-19 20:51 UTC, yvantor approved these changes

2024-06-19 20:53 UTC, yvantor approved these changes
If you are ready I think we can merge this.

2024-06-19 20:53 UTC, yvantor commented
I see there is a bender issue though.

2024-06-24 12:28 UTC, merged